#!/bin/bash
set -euo pipefail

image=$1
version=$2

semver=( ${version//./ } )
minor="${semver[1]}"

declare -a binaries=(kubectl kubelet)

docker create --name hyperkube "$image"
if [ "$minor" -lt "17" ]; then
  docker cp hyperkube:/hyperkube /opt/bin/hyperkube
fi
for binary in "${binaries[@]}"; do
  if [ "$minor" -lt "17" ]; then
    echo "hyperkube $binary "'"$@"' > /opt/bin/"$binary"
    chmod +x /opt/bin/"$binary"
  else
    docker cp hyperkube:/usr/local/bin/"$binary" /opt/bin/"$binary"
  fi
done
docker rm hyperkube
