#!/bin/bash
set -euo pipefail

registry=$1

declare -a binaries=(kubectl kubelet)

for binary in "${binaries[@]}"; do
  docker create --name "$binary" "$registry"/giantswarm/"$binary"
  docker cp "$binary":/usr/local/bin/"$binary" /opt/bin/"$binary"
  docker rm "$binary"
done
