#!/bin/bash
set -euo pipefail

container=$1

docker cp "$container":/hyperkube /opt/bin/hyperkube

docker cp "$container":/usr/sbin/conntrack /opt/bin/conntrack
docker cp "$container":/usr/lib/x86_64-linux-gnu/libnetfilter_conntrack.so.3.6.0 /opt/lib/libnetfilter_conntrack.so.3
docker cp "$container":/lib/x86_64-linux-gnu/libmnl.so.0.2.0 /opt/lib/libmnl.so.0
docker cp "$container":/usr/lib/x86_64-linux-gnu/libnfnetlink.so.0.2.0 /opt/lib/libnfnetlink.so.0

for binary in kubelet kubectl; do
  cat > /opt/bin/"$binary" <<EOF
#!/bin/bash
/opt/bin/hyperkube $binary "\$@"
EOF
  chmod +x /opt/bin/"$binary"
done
