#!/bin/bash
env_file="/etc/apiserver-environment"

cpus="$(grep -c ^processor /proc/cpuinfo)"
memory="$(awk '/MemTotal/ { printf "%d \n", $2/1024/1024 }' /proc/meminfo)"

declare -i cpus
declare -i memory

dedicated=$((cpus * 3 / 4))

echo "MAX_REQUESTS_INFLIGHT=$((dedicated * 200 * 2 / 3))" >$env_file
echo "MAX_MUTATING_REQUESTS_INFLIGHT=$((dedicated * 200 * 1 / 3))" >>$env_file
echo "CPU_LIMIT=${dedicated}" >>$env_file
echo "MEMORY_LIMIT=$((memory * 3 / 4))Gi" >>$env_file
echo "CPU_REQUEST=$((cpus / 2))" >>$env_file
echo "MEMORY_REQUEST=$((memory / 2))Gi" >>$env_file
