#!/bin/bash

# example.com is there to mitigate AWS DNS issues which at startup is able to
# resolve internal AWS DNS names but not public DNS.
domains="{{.Cluster.Etcd.Domain}} {{.Cluster.Kubernetes.API.Domain}} example.com"

for domain in $domains; do
until nslookup $domain; do
    echo "Waiting for domain $domain to be available"
    sleep 5
done

echo "Successfully resolved domain $domain"
done
