apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: calico-init
spec:
  allowedHostPaths:
    - pathPrefix: /etc/kubernetes
      readOnly: true
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  volumes:
    - hostPath
    - secret
---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: calico-init
  name: calico-init
  namespace: kube-system
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: calico-init
  name: calico-init
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - "*"
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - calico-init
    verbs:
    - use
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: calico-init
  name: calico-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-init
subjects:
  - kind: ServiceAccount
    name: calico-init
    namespace: kube-system
