apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: calico-crd-installer
  name: calico-crd-installer
  namespace: kube-system
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: calico-crd-installer
  name: calico-crd-installer
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - "*"
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    resourceNames:
    - privileged
    verbs:
    - use
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: calico-crd-installer
  name: calico-crd-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-crd-installer
subjects:
  - kind: ServiceAccount
    name: calico-crd-installer
    namespace: kube-system
