apiVersion: v1
kind: Pod
metadata:
  name: k8s-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: scheduler
    giantswarm.io/service-type: system
    k8s-app: scheduler
    tier: control-plane
    giantswarm.io/monitoring: "true"
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    prometheus.io/scrape: "true"
    prometheus.io/port: "10251"
    giantswarm.io/monitoring-path: "/metrics"
    giantswarm.io/monitoring-port: "10251"
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: k8s-scheduler
    image: {{ .Images.KubeScheduler }}
    command:
    - kube-scheduler
    - --feature-gates=TTLAfterFinished=true
    - --config=/etc/kubernetes/config/scheduler.yaml
    - --profiling=false
    - --v=2
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/config/
      name: k8s-config
      readOnly: true
    - mountPath: /etc/kubernetes/kubeconfig/
      name: k8s-kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/ssl/
      name: ssl-certs-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/config
    name: k8s-config
  - hostPath:
      path: /etc/kubernetes/kubeconfig
    name: k8s-kubeconfig
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
