apiVersion: v1
kind: Pod
metadata:
  name: k8s-api-healthz
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
    - name: k8s-api-healthz
      command:
        - /k8s-api-healthz
        - --etcd-cert=/etc/kubernetes/ssl/etcd/server-crt.pem
        - --etcd-key=/etc/kubernetes/ssl/etcd/server-key.pem
        - --etcd-ca-cert=/etc/kubernetes/ssl/etcd/server-ca.pem
      image: {{ .Images.KubernetesAPIHealthz }}
      resources:
        requests:
          cpu: 50m
          memory: 20Mi
      volumeMounts:
      - mountPath: /etc/kubernetes/ssl/
        name: ssl-certs-kubernetes
        readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
