#!/bin/bash
domains="{{.Cluster.Etcd.Domain}} {{.Cluster.Kubernetes.API.Domain}} {{ .RegistryDomain }}"

for domain in $domains; do
  if [ "$domain" == "127.0.0.1" ]; then
    echo "Skipping domain check for $domain."
  else
    until nslookup $domain; do
      echo "Waiting for domain $domain to be available"
      sleep 5
    done
    echo "Successfully resolved domain $domain"
  fi
done
