#!/bin/bash

# run `make update-bindata` if any file in the templates directory has been changed

git diff --cached --name-only | grep templates

if [ $? -eq 0 ]; then
  echo 'templates changed, updating bindata'
  make update-bindata
  git add bindata.go
fi
